export const BUILDS_DATA = [
  // Твоя текущая сборка №043 остается первой
  {
    id: "build-043",
    name: "СБОРКА №043",
    price: 150000,
    image: "/assets/images/pc1.png", // Путь к картинке
    cpu: "AMD Ryzen Threadripper 7960X",
    gpu: "NVIDIA RTX 4090 (24 ГБ)",
    ram: "128 ГБ DDR5 ECC",
    ssd: "4 ТБ Gen5 NVMe",
    benchmarks: [
      { label: "Cyberpunk 2077 (4K, Ultra)", value: "85 FPS" },
      { label: "Cinebench R23 (Multi-core)", value: "32500 pts" },
      { label: "Render Time (Blender BMW)", value: "1m 12s" },
    ],
  },
  {
    id: "build-001",
    name: "БЮДЖЕТНЫЙ СТАРТ",
    price: 45000,
    image: "/assets/images/pc1.png",
    cpu: "Intel Core i3-12100F",
    gpu: "NVIDIA GTX 1650",
    ram: "16 ГБ DDR4",
    ssd: "512 ГБ NVMe",
    benchmarks: [
      { label: "CS 2 (1080p, High)", value: "120 FPS" },
      { label: "Dota 2 (1080p, Ultra)", value: "95 FPS" },
      { label: "Geekbench 6 (Single-core)", value: "1850 pts" },
    ],
  },
  {
    id: "build-002",
    name: "CORE GAMER",
    price: 85000,
    image: "/assets/images/pc1.png",
    cpu: "AMD Ryzen 5 5600",
    gpu: "NVIDIA RTX 3060",
    ram: "16 ГБ DDR4",
    ssd: "1 ТБ NVMe",
    benchmarks: [
      { label: "Atomic Heart (1080p, Atomic)", value: "75 FPS" },
      { label: "Forza Horizon 5 (1080p, Extreme)", value: "88 FPS" },
      { label: "3DMark Time Spy", value: "9200 pts" },
    ],
  },
  {
    id: "build-003",
    name: "WHITE EDITION",
    price: 110000,
    image: "/assets/images/pc1.png",
    cpu: "Intel Core i5-13400F",
    gpu: "NVIDIA RTX 4060 Ti White",
    ram: "32 ГБ DDR5",
    ssd: "1 ТБ NVMe",
    benchmarks: [
      { label: "Cyberpunk 2077 (1080p, High, DLSS)", value: "90 FPS" },
      { label: "The Witcher 3 Next-Gen (1080p)", value: "72 FPS" },
      { label: "Cinebench R23", value: "14800 pts" },
    ],
  },
  {
    id: "build-004",
    name: "STREAMER PRO",
    price: 135000,
    image: "/assets/images/pc1.png",
    cpu: "AMD Ryzen 7 7700X",
    gpu: "NVIDIA RTX 4070 Super",
    ram: "32 ГБ DDR5",
    ssd: "2 ТБ NVMe",
    benchmarks: [
      { label: "Warzone 3 (1440p, Competitive)", value: "145 FPS" },
      { label: "OBS Encoding Test (4K60)", value: "0% Dropped" },
      { label: "V-Ray Benchmark", value: "12500 vps" },
    ],
  },
  {
    id: "build-005",
    name: "BLACK MONOLITH",
    price: 195000,
    image: "/assets/images/pc1.png",
    cpu: "Intel Core i7-14700K",
    gpu: "NVIDIA RTX 4080 Super",
    ram: "64 ГБ DDR5",
    ssd: "2 ТБ NVMe",
    benchmarks: [
      { label: "Alan Wake 2 (1440p, High, RT)", value: "78 FPS" },
      { label: "Starfield (1440p, Ultra)", value: "85 FPS" },
      { label: "Cinebench R23", value: "34000 pts" },
    ],
  },
  {
    id: "build-006",
    name: "WORKSTATION X",
    price: 240000,
    image: "/assets/images/pc1.png",
    cpu: "AMD Ryzen 9 7950X",
    gpu: "NVIDIA RTX 4090",
    ram: "64 ГБ DDR5",
    ssd: "4 ТБ NVMe",
    benchmarks: [
      { label: "OctaneRender (Bench)", value: "650 pts" },
      { label: "Blender Classroom Render", value: "3m 45s" },
      { label: "PugetBench Premiere Pro", value: "1150 pts" },
    ],
  },
  {
    id: "build-007",
    name: "MINI-ITX BEAST",
    price: 125000,
    image: "/assets/images/pc1.png",
    cpu: "Intel Core i5-13600K",
    gpu: "NVIDIA RTX 4070",
    ram: "32 ГБ DDR5",
    ssd: "1 ТБ NVMe",
    benchmarks: [
      { label: "Spider-Man Remastered (1440p, Ultra)", value: "110 FPS" },
      { label: "Temp Test (Max Load)", value: "74°C" },
      { label: "3DMark Fire Strike", value: "28500 pts" },
    ],
  },
  {
    id: "build-008",
    name: "ENTRY LEVEL V2",
    price: 55000,
    image: "/assets/images/pc1.png",
    cpu: "AMD Ryzen 5 3600",
    gpu: "AMD Radeon RX 6600",
    ram: "16 ГБ DDR4",
    ssd: "512 ГБ NVMe",
    benchmarks: [
      { label: "PUBG (1080p, Ultra)", value: "105 FPS" },
      { label: "Valorant (1080p, Low)", value: "380 FPS" },
      { label: "PCMark 10 Extended", value: "7200 pts" },
    ],
  },
  {
    id: "build-009",
    name: "ULTIMATE GAMING",
    price: 320000,
    image: "/assets/images/pc1.png",
    cpu: "Intel Core i9-14900KS",
    gpu: "NVIDIA RTX 4090 OC",
    ram: "96 ГБ DDR5",
    ssd: "4 ТБ Gen5",
    benchmarks: [
      { label: "Cyberpunk 2077 (4K, RT Overdrive)", value: "95 FPS" },
      { label: "Microsoft Flight Sim (4K, Ultra)", value: "110 FPS" },
      { label: "3DMark Port Royal", value: "26000 pts" },
    ],
  },
  {
    id: "build-010",
    name: "SILENT NIGHT",
    price: 165000,
    image: "/assets/images/pc1.png",
    cpu: "AMD Ryzen 7 7800X3D",
    gpu: "NVIDIA RTX 4070 Ti",
    ram: "32 ГБ DDR5",
    ssd: "2 ТБ NVMe",
    benchmarks: [
      { label: "Elden Ring (1440p, Max)", value: "60 FPS (Locked)" },
      { label: "Noise Level (Full Load)", value: "28 dB" },
      { label: "Shadow of the Tomb Raider", value: "155 FPS" },
    ],
  },
];
